function x = display(d)
%DISPLAY Basic template for the optimizer routines of the interior point family
%	
%	X = DISPLAY(D) when called with an output argument prints out
%	the parameter setting which can be used with a logfile

% File:        @pr_smo/display.m
%
% Author:      Alexandros Karatzoglou
% Created:     24/02/04
% Updated:     24/02/04
%
% This code is released under the GNU Public License
% Copyright by GMD FIRST and The Australian National University

if nargout == 0
  tmp = sprintf(['Sequential Minimal Optimizer for Pattern Recognition\n' ...
		 'C          \t: %d\n' ...
		 'epsilon    \t: %d\n' ...
		 'tol        \t: %d\n' ...
		 'numbers changed\t: %d\n' ...
		 'examine all\t: %d\n' ...
		 'counter      \t: %d\n' ...
		 'filename      \t: %s\n' ...
		 'verbose       \t: %d'], ...
		d.C, d.epsilon, d.tol, d.numchanged, d.examineall, ...
	d.counter, d.filename, d.verbose);
  disp(tmp);
else
  x = sprintf('%d_C_%d_epsilon_%d_tol_%d_numchanged_%d_examineall_%d_counter_%s_filename_%d_verbose', ...
	      d.C, d.epsilon, d.tol, d.numchanged, d.examineall, d.counter,d.filename,d.verbose);
end
