function b=consistent(da)
% b=consistent(da)

b=(size(da.train_pat,2)==size(da.train_targ,2)) & ...
  (size(da.test_pat,2)==size(da.test_targ,2)) & ...
  (size(da.val_pat,2)==size(da.val_targ,2)) & ...
  ((size(da.val_pat,1)==size(da.train_pat,1)) | (size(da.val_pat,1)==0))& ...
  ((size(da.test_pat,1)==size(da.train_pat,1)) | (size(da.test_pat,1)==0)) & ...
  ((size(da.val_targ,1)==size(da.train_targ,1)) | (size(da.val_pat,1)==0)) & ...
  ((size(da.test_targ,1)==size(da.train_targ,1)) | (size(da.test_pat,1)==0)) ;